### ISSUE TITLE
PDF rendering (DomPDF)  elimination ladder stopped working

### ISSUE THREAD

**Issue by zongordon** [zongordon/CORS#62]
Error message when clicking to render a PDF elimination ladder:
Uncaught Error: Class "Dompdf\Cpdf" not found in /var/www/tunakaratecup.com/dompdf/src/Adapter/CPDF.php:177 Stack trace: #0 /var/www/tunakaratecup.com/dompdf/src/CanvasFactory.php(56): Dompdf\Adapter\CPDF->__construct('letter', 'portrait', Object(Dompdf\Dompdf)) #1 /var/www/tunakaratecup.com/dompdf/src/Dompdf.php(274): Dompdf\CanvasFactory::get_instance(Object(Dompdf\Dompdf), 'letter', 'portrait') #2 /var/www/tunakaratecup.com/testsite/DomPDF.php(23): Dompdf\Dompdf->__construct() #3 {main} thrown in /var/www/tunakaratecup.com/dompdf/src/Adapter/CPDF.php on line 177

**Comment by zongordon** [comment]
Solved by commit v3.4.3
